"""fixed relationships n updated tables

Revision ID: 1055b5c5a154
Revises: bbd8df9eba03
Create Date: 2024-08-15 22:32:13.163139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1055b5c5a154'
down_revision = 'bbd8df9eba03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licenses')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_customer_id_customers', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_car_id_cars', type_='foreignkey')
        batch_op.drop_column('car_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('car_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_reviews_car_id_cars', 'cars', ['car_id'], ['id'])
        batch_op.create_foreign_key('fk_reviews_customer_id_customers', 'customers', ['customer_id'], ['id'])

    op.create_table('licenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('license_number', sa.VARCHAR(), nullable=True),
    sa.Column('expiration_date', sa.DATE(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_licenses_customer_id_customers'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    # ### end Alembic commands ###
