"""esablished a relationship between cars and reviews v2

Revision ID: 2c14c0210714
Revises: 5978b2ec4199
Create Date: 2024-08-30 06:30:27.456655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c14c0210714'
down_revision = '5978b2ec4199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_car_review_car_id_cars'), 'cars', ['car_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_car_review_car_id_cars'), type_='foreignkey')
        batch_op.drop_column('car_id')

    # ### end Alembic commands ###
