"""fixed messed relationships

Revision ID: 5978b2ec4199
Revises: e13a9ba6d4b0
Create Date: 2024-08-29 13:01:10.707962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5978b2ec4199'
down_revision = 'e13a9ba6d4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_car_review_car_id_cars', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_car_review_customer_id_customers'), 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('car_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_car_review_customer_id_customers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_car_review_car_id_cars', 'cars', ['car_id'], ['id'])
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
