"""updated customer table

Revision ID: e3b1041a3b5e
Revises: 1055b5c5a154
Create Date: 2024-08-18 20:24:10.282753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b1041a3b5e'
down_revision = '1055b5c5a154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_car_id_cars', type_='foreignkey')
        batch_op.drop_column('car_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_customers_car_id_cars', 'cars', ['car_id'], ['id'])

    # ### end Alembic commands ###
